### ISSUE TITLE
CSVWriter

### ISSUE THREAD

**Issue by gtc309** [gtc309/otr#2]
Where is a good copy of the CSVwriter jar?

**Comment by nwork** [comment]
i have no idea, i have never seen it. first time i knew of it was this morning.

________________________________

**Comment by gtc309** [comment]
May be Steve has a good copy, the one I found does not seem to work.

**Comment by nwork** [comment]
I found one on sourceforge, it seems to work

http://sourceforge.net/projects/javacsv/?source=typ_redirect

________________________________

**Comment by basedProgrammerGod** [comment]
I don't know if one is even started.

**Comment by TheGreenDragon** [comment]
Sorry for the delay in responding. I have not been feeling well the last
couple days. I got it from the following:

http://sourceforge.net/projects/javacsv/

**Comment by TheGreenDragon** [comment]
Here is the direct link I used to download the jar file.
http://sourceforge.net/projects/javacsv/files/JavaCsv/JavaCsv%202.1/

**Comment by gtc309** [comment]
Got it and it is working.

**Comment by TheGreenDragon** [comment]
SWEET!!!!
