### ISSUE TITLE
datastor not writing

### ISSUE THREAD

**Issue by gtc309** [gtc309/otr#4]
An array filled with informatin is going to datastor, but datastor is not writing the headers or array data into the file. An empty file is created.

**Comment by TheGreenDragon** [comment]
I have found two small issues with the code and am addressing them. We are
having connectivity issues at the house preventing me from researching the
issue. I will continue debugging and post changes asap.

**Comment by TheGreenDragon** [comment]
It is writing now but the variables are not coming in the way I expected. I will look at them tonight/tomorrow and adjust the headers to match.

**Comment by TheGreenDragon** [comment]
Resolved

**Comment by gtc309** [comment]
I ran it and it is writing, the variables are correct as we do not add
padding to them anywhere in the program. When I pulled this last time
the remote put a otr2.com branch on my system which contained a version
of csvwriter, I had to remove that before the system ran correctly.
csvWriter should be put in with your other libraries.

**Comment by TheGreenDragon** [comment]
I found the issue with the variables earlier, I had forgotten to include one of the headers. Completely my fault and already fixed in the last push. As for moving the csvwriter, it will not build on my system unless they are in that exact location. Perhaps it is a setting i am missing with my ide?

**Comment by TheGreenDragon** [comment]
Updated again, It is working on my end.

**Comment by gtc309** [comment]
In Netbeans you would right click on the proect name go to properties then select, go to add jar button then navigate to the jar file you are adding.
